### PR TITLE
[ABC-493] Add missing hair groom icon

### PR DESCRIPTION
**Pull request by thomas-tu**
## Purpose of this PR

**Ticket/Jira #:**

image
image

## Testing

**Functional Testing status:**

CI tests + manual tests in Light+Dark modes.

**Performance Testing status:**

None
## Overall Product Risks

**Complexity:** Low

**Halo Effect:** Minimal

## Documentation & UX Writing

| User facing text to review |  | Details |
| :--- | :--- | :--- |
| User interface | N |  |
| Public API docs | N |  |
| Changelog | N |  |

| Documentation halo effect |  | Jira link |
| :--- | :--- | :--- |
| User manual | Y |  |
| Other docs | N |  |

## Additional information

**Note to reviewers:**

### CODE REVIEW

**Review by SanaJal — COMMENTED** [review]
image
Tested on 2023.3 on Windows. The icon seems bigger than the one in the PR description. It's also not aligned with the title.

**Comment by thomas-tu** [comment]
> image Tested on 2023.3 on Windows. The icon seems bigger than the one in the PR description. It's also not aligned with the title.

Issue should not occur with [ffaf839](https://github.com/Unity-Technologies/com.unity.formats.alembic/pull/586/commits/ffaf839b258bea7f73a3a9dd3b8f7741b4373945).

**Comment by thomas-tu** [comment]
Look should be good now. cc @cguer

**Review by SanaJal — APPROVED** [review]
LGTM !

**Pull request merged**
